add docker(microservice) RFC
FlickerSoul/Graphery pull request #88
Opened 2020-12-24 12:13 UTC by jukrb0x

Leave some thoughts about implementing in Graphery with docker, plz review && correct.

2020-12-24 17:10 UTC, FlickerSoul requested changes
Please elaborate on your frontend RFC?

2021-01-12 01:50 UTC, jukrb0x commented
The RFC is updated.

2021-01-20 12:34 UTC, jukrb0x commented
This PR is way too chaotic, so far, we've done:
- add RFC for docker (low priority)
- update the RFC for frontend
-  update styles (to be continued)

2021-01-21 21:14 UTC, FlickerSoul approved these changes

2021-01-21 21:14 UTC, FlickerSoul commented on graphery/src/views/Home.vue
> +    <!--          </q-btn>-->
remove comments

2021-01-21 21:14 UTC, merged